### ISSUE TITLE
Link to the website is missing!

### ISSUE THREAD

**Issue by seifsg** [MTanabene/MTanabene.github.io#1]
Good job on uploading your first on GitHub pages.
I just want to mention that it would've been better if a link was presented in the readme file.

Keep up the good work :thumbsup:

**Comment by MTanabene** [comment]
Thank you for your great remark and pushing comment. ❤️ 
I am learning from your feedback! 👍  If it will be better, I will add it 🔗 now. 

Yeah, sure I will keep going!
